name: Deploy to WebServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate random ID
        run: echo "RANDOM_ID=$(uuidgen)" >> $GITHUB_ENV;
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV;

      - name: Branch to preview
        if: ${{ vars.DEPLOY_BRANCH == 'preview' }}
        uses: actions/checkout@v4
        with:
          ref: preview

      - name: Checkout source
        if: "!(${{ vars.DEPLOY_BRANCH == 'preview' }})"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compress build directory
        run: |
            cd ${{ vars.DEPLOY_DIR }} ;
            tar -zcf /tmp/$REPO_NAME.tar.gz .;
            ls -la /tmp/$REPO_NAME.tar.gz

      - name: Upload via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_scp }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          source: "/tmp/$REPO_NAME.tar.gz"
          target: "/tmp/dep/"

      - name: Extract on remote
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            hostname;
            cd /srv/www/html;
            mkdir -p $REPO_NAME/htdocs;
            cd $REPO_NAME/htdocs;
            tar zxf /tmp/dep/tmp/$REPO_NAME.tar.gz
