name: Deploy to WebServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Branch to preview
        if: ${{ vars.DEPLOY_BRANCH == 'preview' }}
        uses: actions/checkout@v4
        with:
          ref: preview

      - name: Checkout source
        if: "!(${{ vars.DEPLOY_BRANCH == 'preview' }})"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract on remote
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            hostname
