name: Deploy to WebServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Branch to preview
        if: ${{ vars.DEPLOY_BRANCH == 'preview' }}
        uses: actions/checkout@v4
        with:
          ref: preview

      - name: Checkout source
        if: "!(${{ vars.DEPLOY_BRANCH == 'preview' }})"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compress build directory
        run: |
            cd ${{ vars.DEPLOY_DIR }} ;
            mkdir /tmp/dep;
            tar -zcf /tmp/dep/deploy.tar.gz .;
            ls -la /tmp/dep/deploy.tar.gz

      - name: Upload via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_scp }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          source: "/tmp/dep/deploy.tar.gz"
          target: "/tmp/dep/"

      - name: Extract on remote
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            hostname;
            cd /srv/www/html;
            mkdir test-rep;
            cd test-tep;
            tar zxf /tmp/deploy.tar.gz
